name: action-pr
on:
  pull_request:
    branches: "master"
    types: [opened, reopened, synchronize]

  workflow_dispatch:
jobs:
  action-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install & vercel
